FROM node:lts-alpine AS buildStep

WORKDIR /client

COPY package.json /client

RUN npm install

COPY . /client

RUN npm run build

FROM nginx:latest 

ENV PORT=8080

COPY --from=buildStep /client/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'